---
title: "CDT Colum"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(dplyr)
library(readxl)
library(tidyverse)
```


```{r echo=FALSE}
# Directory containing .xlsx files
data_folder <- "data"

# List all .xlsx files in the data folder
xlsx_files <- list.files(path = data_folder, pattern = "\\.xlsx$", full.names = TRUE)

# Extract file names without extension
file_names <- tools::file_path_sans_ext(basename(xlsx_files))

# Create checkbox group dynamically
checkboxGroupInput("fileCheckboxes", "Select files:", choices = file_names)
```

```{r}
# Read selected files and display their content
renderUI({
  req(input$fileCheckboxes)
  
  tables <- lapply(input$fileCheckboxes, function(file) {
    path <- file.path("data", paste0(file, ".xlsx"))
    data <- read_excel(path)

    Plot <-
      ggplot(data, aes(x = DepSM, y = SeaTurbMtr)) +
      geom_line()+
      scale_y_reverse()
      

    renderPlot(Plot)
  })
  
  do.call(tagList, tables)
})
```

